catalog:
    typescript: '^7.0.1-rc'
minimumReleaseAgeExclude:
    - '@typescript/native-preview-darwin-arm64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-darwin-x64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-linux-arm64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-linux-arm@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-linux-x64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-win32-arm64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview-win32-x64@7.0.0-dev.20260620.1'
    - '@typescript/native-preview@7.0.0-dev.20260620.1'
overrides:
    '@typescript-eslint/project-service>typescript': 'catalog:'
    '@typescript-eslint/tsconfig-utils>typescript': 'catalog:'
    '@typescript-eslint/typescript-estree>typescript': 'catalog:'
    '@typescript-eslint/utils>typescript': 'catalog:'
    minimatch>brace-expansion: '^5.0.6'
