jobs:
  publish:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: 'ubuntu-24.04'
    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v6'
      - name: 'Setup pnpm'
        uses: 'pnpm/action-setup@v6'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v7'
        with:
          cache: 'pnpm'
          node-version: 26
      - name: 'Install dependencies'
        run: 'pnpm ci'
      - name: 'Publish'
        run: 'npx jsr publish'
name: 'Publish'
on:
  workflow_dispatch:
